# CamlGI configuration                                -*- Makefile -*-
# Copyright (C) Christophe TROESTLER
#
# $(PKGNAME) and $(PKGVERSION) are defined.

# OCAMLC, OCAMLOPT, OCAMLDEP, OCAMLDOC
# The location of the OCaml compiler and tools. The defaults should be OK.
#
OCAMLFIND = ocamlfind
OCAMLC = $(OCAMLFIND) ocamlc
OCAMLOPT = $(OCAMLFIND) ocamlopt
OCAMLDEP = $(OCAMLFIND) ocamldep
OCAMLDOC = $(OCAMLFIND) ocamldoc

PREFIX ?= /usr/local

# OCAMLLIBDIR: location of OCaml's library files.
# Set it if you want another directory than the default findlib directory.
#OCAMLLIBDIR = $(PREFIX)/lib/ocaml/$(shell ocamlc -version)

# DOCDIR: where we will install the documentation.
#
DOCDIR ?= $(PREFIX)/doc/$(PKGNAME)-$(PKGVERSION)
